version: 2.1

jobs:
  set_nvm:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: |
          node -v
      - run: |
          nvm install v15.11.0
          node -v
          sudo -Hi nvm alias default v15.11.0
      - run: |
          node -v
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          name: Check FUSE
          command: |
            # https://stackoverflow.com/questions/16991414/which-fuse-version-in-my-kernel
            fusermount -V
            dpkg --get-selections | grep fuse
      - run:
          name: Check Python
          command: python --version
      - run:
          name: Install Python packages
          command: |
            pip install futures
            pip install --upgrade awscli
      - run:
          name: Confirm package version
          command: |
            pip show awscli
            pip show rsa

workflows:
  main:
    jobs:
      # - build
      - set_nvm
