version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          name: Check FUSE
          command: |
            # https://stackoverflow.com/questions/16991414/which-fuse-version-in-my-kernel
            fusermount -V
            dpkg --get-selections | grep fuse
      - run:
          name: Check Python
          command: python --version
      - run:
          name: Install Python packages
          command: |
            pip install futures
            pip install --upgrade awscli
      - run:
          name: Confirm package version
          command: |
            pip show awscli
            pip show rsa

workflows:
  main:
    jobs:
      - build
