version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run:
          name: Check Python
          command: python --version
      - run:
          name: Install Python packages
          command: |
            pip install futures
            pip install --upgrade awscli
      - run:
          name: Confirm package version
          command: |
            pip show awscli
            pip show rsa

workflows:
  main:
    jobs:
      - build
