version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.4-node
    steps:
      - run:
          name: Check Python
          command: python --version
      - run:
          name: Install Python packages
          command: |
            pip install futures
            pip install --upgrade awscli

workflows:
  main:
    jobs:
      - build
