version: 2.1

parameters:
  scheduled:
    type: boolean
    default: false

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello, from schedule"

  set_nvm:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && source $NVM_DIR/nvm.sh' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> $BASH_ENV
      - run: |
          node -v
      - run: |
          nvm install v15.11.0
          node -v
          nvm alias default v15.11.0
          printenv PATH
          echo 'export PATH=/opt/circleci/.nvm/versions/node/v15.11.0/bin:$PATH' >> $BASH_ENV
          cat $BASH_ENV
      - run: |
          cat $BASH_ENV
          printenv PATH
          nvm current
          node -v
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          name: Check FUSE
          command: |
            # https://stackoverflow.com/questions/16991414/which-fuse-version-in-my-kernel
            fusermount -V
            dpkg --get-selections | grep fuse
      - run:
          name: Check Python
          command: python --version
      - run:
          name: Install Python packages
          command: |
            pip install futures
            pip install --upgrade awscli
      - run:
          name: Confirm package version
          command: |
            pip show awscli
            pip show rsa

workflows:
  main:
    when:
      not: << pipeline.parameters.scheduled >>
    jobs:
      # - build
      - set_nvm

  scheduled:
    when: << pipeline.parameters.scheduled >>
    jobs:
      - hello
